language: minimal 
before_install:
- sudo apt-get update
- sudo apt-get install texlive texlive-latex-extra texlive-publishers
- sudo apt-get install latexmk
script:
- make
after_success:
- "curl -F "file=@main.pdf" https://file.io"
